apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend-frontend-poi-map-app-dev
  annotations:
    argocd/app-name: frontend-frontend-poi-map-app-dev
    backstage.io/kubernetes-id: frontend-frontend-poi-map-app-dev
    backstage.io/kubernetes-namespace: frontend
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=frontend-frontend-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/frontend-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/frontend/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/frontend/deployments/frontend-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/frontend-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://frontend-poi-map-app-frontend.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "asshutossh"
  system: workshop-system-frontend
  consumesApis:
    - gateway-api-frontend
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-frontend
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "asshutossh"
